server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/db_satset?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
# Kosongkan password jika di MySQL memang tidak diatur password
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true