spring.application.name=SatSet
# Koneksi Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/satset_db
spring.datasource.username=postgres
spring.datasource.password=satsetitenice
spring.datasource.driver-class-name=org.postgresql.Driver

# Konfigurasi Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Static Resources
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=31536000
spring.web.resources.chain.cache=true
spring.web.resources.chain.compressed=true
spring.web.resources.chain.gzipped=true
